### ISSUE TITLE
History service: GET /transactions to return failed, pending and incoming transactions

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-relay-service#118] opened 2019-06-20 10:05 UTC
# What is needed?

We need  GET /transactions endpoint to return failed, pending and incoming transactions.

# Why is it needed?

It's easier for the users to track all the transactions without leaving the Safe app and searching through etherscan. This would be really helpful for users which are not that familiar with the Etherum.

# When is it needed?

Sometime in the future. For v0.1.0 we decided not to include incoming ones, not sure about pending and failed ones. Will update the issue once we discuss it

**Comment by rmeissner** [comment] 2019-06-20 10:28
duplicate of #105

**Closed by rmeissner** 2019-06-20 10:28 UTC
